### ISSUE TITLE
Word Drop

### ISSUE THREAD

**Issue by momopusheen** [silent-chen/layout-guidance#11]
Hi @silent-chen , thanks for your brilliant work!

I'm interested in Word Drop. As you mentioned in the paper, images generated with padding (i.e., nonword) token embeddings closely follow both the semantics and the layout of the image generated from the full-text prompt. 

Would you also be able to share the code of Word Drop?  I can't wait to know more details about it. 😊

Thanks again!

**Comment by silent-chen** [comment]
Sure. The idea is to use the [EoT] token to replace the word token. 
``` 
# Find the position of the first [EoT].
for i in range(77):
    if input_ids[i] == 49407:
        first_padding = i
for i in range(1, first_padding):
    cond_text_embeddings[0][i] = cond_text_embeddings[0][first_padding]
```
If you have further questions, please let me know.

**Comment by momopusheen** [comment]
Got it! You've been a great help! 😊
