### ISSUE TITLE
When will the real image editing released

### ISSUE THREAD

**Issue by RunpuWei** [silent-chen/layout-guidance#15]
Dear author.

Thank you for your awesome work, and congratulations on your work being accepted by WACV2024.

I wonder when the real image editing will be released, I am very interested in your work and hope to replicate it. 

Thank you!

**Comment by silent-chen** [comment]
Hi, thanks for your interest in our work. I plan to release the real image editing part within this month. Hope it can inspire you somehow.

**Comment by silent-chen** [comment]
Sorry for the late update. I was kind of busy last month. I will try to clean up the code and release it soon.

**Comment by RunpuWei** [comment]
Thank you for your hard work. Looking forward to it!

**Comment by Sjey-Lyn** [comment]
Has real image editing been released yet?

**Comment by silent-chen** [comment]
Hi all, sorry for the late release. I just cleaned the real image editing code and pushed it to the repo. I also updated the dependent library because the CLIPFeatureExtractor is now deprecated in diffusers now. Please update the corresponding libs. Let me know if you have further questions.

**Comment by Sjey-Lyn** [comment]
I'm using a 4090 and it's showing that I don't have enough cuda memory, what is the minimum amount of  memory needed?

**Comment by silent-chen** [comment]
It will cost ~28GB memory for text inversion and ~31GB for Dreambooth. To reduce the GPU memory usage in text inversion, you can try to reduce the batch size for text inversion by setting `batch_size` in `conf/real_image_editing_config.yaml `. To get similar results as using a batch size of 4, please use accumulated gradient and increase the iteration numbers 
accordinately.  For dreambooth, it requires at least 30GB. You can probably reduce the memory usage by using xformers.
