### ISSUE TITLE
Can I use negative prompt?

### ISSUE THREAD

**Issue by Veremay** [silent-chen/layout-guidance#19]
I find that things that do not appear in my prompt often appear in the generated images, including watermarks and so on. 

Can I enter a negative prompt to avoid this problem? If it can be entered, where can I add it?

**Comment by silent-chen** [comment]
Hi, thanks for your interest in our paper. It is possible to add negative prompts. Typically, you should replace the unconditional token with the negative token. To be specifically, you should change the empty list [here](https://github.com/silent-chen/layout-guidance/blob/08b687470f911c7f57937012bdf55194836d693e/inference.py#L26C5-L26C17) to the negative prompt that you don't want. A more detailed explanation can be found [here](https://github.com/huggingface/diffusers/blob/v0.26.2/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L118).
