### ISSUE TITLE
Setting Problems

### ISSUE THREAD

**Issue by YYYYYHC** [silent-chen/layout-guidance#3]
Thank you for the exciting work!

I try to run the demo following the instruction, but I can not automatically download the model (CLIP, UNet, etc.), so I want to know your setting for these models and download them manually.

I'm looking forward to hearing back from you.

**Comment by silent-chen** [comment]
Hi, thanks for your interest in our project. I am using the models [Here](https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main). For the downloading error, it might be related to the Hugging face setting.
