### ISSUE TITLE
Variable Issue

### ISSUE THREAD

**Issue by BryceRosky** [silent-chen/layout-guidance#4]
Dear author,

Hello. I encountered an issue while running your code. The variable "attn_num_head_channels" is set as a list, which results in the error message "TypeError: unsupported operand type(s) for //: 'int' and 'list'".

**Comment by xiaominli1020** [comment]
Hello, I met the same problem, how did you solve it?
thx

**Comment by BryceRosky** [comment]
Hello Xiaomin:
Maybe you should train the stable diffusion use the same version of diffuser  as the lay out guidance

---- Replied Message ----
| From | Xiaomin ***@***.***> |
| Date | 09/12/2023 15:17 |
| To | silent-chen/layout-guidance ***@***.***> |
| Cc | BryceRosky ***@***.***>,
State ***@***.***> |
| Subject | Re: [silent-chen/layout-guidance] Variable Issue (Issue #4) |

Hello, I met the same problem, how did you solve it?
thx
