### ISSUE TITLE
subject-driven issue

### ISSUE THREAD

**Issue by BryceRosky** [silent-chen/layout-guidance#5]
Dear author,

I have discovered an issue when attempting to generate a specific subject using the fine-tuned model from Dreambooth. The problem lies in the variable "attn_num_head_channels" being assigned a list type, resulting in the error message "TypeError: unsupported operand type(s) for //: 'int' and 'list'". Could you please provide guidance on a potential solution for this?

Thank you.

**Comment by silent-chen** [comment]
Hi, 

Thanks for your interest in our work. I am not sure about the answer but it might be something related to the diffuser version. I found a related problem [here](https://huggingface.co/stabilityai/stable-diffusion-2/discussions/29).
