### ISSUE TITLE
Out-of-memory issue

### ISSUE THREAD

**Issue by zykev** [silent-chen/layout-guidance#6]
Dear authors,

Thanks for your exciting work. I'm trying to run inference.py to see some generated images. But I get the OOM error though I use Nvidia 2080Ti. I'd like to know how much gpu memory is proper for inference. Is there anything to adjust to decrease the demand on memory like changing the size of generated images?

**Comment by silent-chen** [comment]
Hi, thanks for your interest. The GPU memory requirement is at least 14GB. I don't recommend changing the size of generated images since the stable diffusion model does not get the best results under other resolution settings.
