### ISSUE TITLE
Real Image Editing

### ISSUE THREAD

**Issue by dripdropdr** [silent-chen/layout-guidance#7]
Dear author. 

First, thank you for your awesome work! 
I wonder this code has any plan to support real image editing.
If not, I want to ask you implementation detail of real image editing with layout guidance.

Thank you!

**Comment by silent-chen** [comment]
Hi, thanks for your interests in our work. Yes, we have a plan to release a tutorial about real image editing later.

**Comment by JoshonSmith** [comment]
> 
I also want to learn about the implementation detail of real image editing with layout guidance.
Thanks !


> Hi, thanks for your interests in our work. Yes, we have a plan to release a tutorial about real image editing later.

**Comment by Bailey-24** [comment]
how to edit the real image

**Comment by silent-chen** [comment]
Please see the response to  #15
