### ISSUE TITLE
TypeError: unsupported operand type(s) for //: 'int' and 'list'

### ISSUE THREAD

**Issue by xiaominli1020** [silent-chen/layout-guidance#8]
Hello, I met the same problem as follows, could you please tell me how to solve it?

https://github.com/silent-chen/layout-guidance/issues/4#issue-1781940936

**Comment by silent-chen** [comment]
Hi, thanks for your interest in our work. Did you try the diffuser version listed in the requirements? If you have tried that, could you share your running environment?

**Comment by WangJiuniu** [comment]
Hello, I met the same problem because I tried to use stable diffusion v2.1 checkpoint. I solved this problem by using stable diffusion v1.5 as guided in the code.

Good luck!
