### ISSUE TITLE
where is latents = 1 / 0.18215 * latents from?

### ISSUE THREAD

**Issue by edhuang1** [silent-chen/layout-guidance#9]
Thank you for your excellent work.

Could you pls explain the code latents = 1 / 0.18215 * latents?
where is 1 / 0.18215 from? 

Best wishes,

**Comment by silent-chen** [comment]
Hi, thanks for your interest in our work. This is scaling factor of VAE, please check [here](https://github.com/huggingface/diffusers/blob/16b9a57d29b6dbce4f97dbf439af1663d2c54588/src/diffusers/models/autoencoder_kl.py#L68).
